config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pages#index"
  get "/contact", to: "pages#contact"
  post "/request_form_submissions/create", to: "request_form_submissions#create"
end

app/views/pages/contact.html.erb
<div class="banner normal-page-banner">
  <div class="background-overlay">
	  <div class="banner-container">
	    <h1 class="normal-page-heading">Contact</h1>
	    <p>Get in touch with our team of professional and let us take care of the rest.</p>
	  </div>
  </div>
</div>

<div class="two-columns-section-container">
  <section class="two-columns-section">
  	<div class="two-columns-left-column">
  	  <div class="left-column-container">
	  	<div class="sub-section">
	      <h6 class="sub-heading">Get in touch</h6>
	    </div>
	    <div class="sub-section">
	      <h2>Send Message</h2>
	    </div>
	    <div class="sub-section">
	      <p>
	        Lorem ipsum dolor sit amet consectetur adipiscing elit do eiusmod tempor incididunt ut  nisi ut aliquip ex ea commodo consequat.
	      </p>
	    </div>
	    <div class="sub-section contact-details">
	      <div class="location-icon">
	      	<i class="fa-solid fa-location-dot"></i>
	      </div>
	      <div class="contact-details-content">
	      	<h6 class="sub-heading">Head Office</h6>
	      	<p>Amphitheatre Parkway, Mountain View, California, USA 94043</p>
			<ul class="contact-details-content-list">
			  <li>
				<a href="#">
				  <span class="list-icon">
				    <i aria-hidden="true" class="far fa-envelope"></i>
				  </span>
				  <span class="list-text">mail@coorp.co</span>
				</a>
			  </li>
			  <li>
			    <a href="#">
				  <span class="list-icon">
				    <i aria-hidden="true" class="fas fa-mobile-alt"></i>
				  </span>
				  <span class="list-text">+123 456 789</span>
				</a>
			  </li>
			</ul>
	      </div>
	    </div>
	  </div>
  	</div>
  	<div class="two-columns-right-column">
  		<div class="form-container">
	  		<div class="form-section">
				  <%= form_with(model: @request, url: request_form_submissions_create_path, method: "POST") do |form| %>
			  		<div class="form-item">
						  <label for="request_form_submission_name">
						    Name
						  	<span class="blue-text">*</span>
						  </label>
						  <%= form.text_field :name, class: "contact-form-input", required: true %>
					  </div>
				  	<div class="form-item">
						  <label for="request_form_submission_email">
						  	Email
						  	<span class="blue-text">*</span>
						  </label>
		  				<%= form.text_field :email, class: "contact-form-input", required: true %>
	  				</div>
					  <div class="form-item">
						  <label for="request_form_submission_comment">
						    Message
						  	<span class="blue-text">*</span>
						  </label>
					  	<%= form.text_area :comment, required: true %>
				  	</div>

			  		<div>
		  				<%= form.submit "Send Message", class: "button button-secondary" %>
	  				</div>
				  <% end %>
			  </div>
			</div>
  	</div>
  </section>
</div>
<div class="contact-map">
<iframe frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.com/maps?q=amphitheater%20parkway%2C%20mountain%20view%2C%20CA%2C%2094043&amp;t=m&amp;z=15&amp;output=embed&amp;iwloc=near" title="amphitheater parkway, mountain view, CA, 94043" aria-label="amphitheater parkway, mountain view, CA, 94043"></iframe>
</div>

app/views/pages/index.html.erb
<div class="banner">
  <div class="background-overlay">
		<div class="banner-container">
	  	<h1>Smart Business Solution for Better Future</h1>
		  <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit luctus ullamcorper mattis.</p>
      <a href="#" class="button button-primary">Get Started</a>
    </div>
  </div>
</div>
<div class="featured-links-container">
	<div class="featured-links">
		<div class="featured-link">
			<i class="fa-solid fa-pencil icon"></i>
			<span class="icon-text">Register your email</span>
		</div>
		<div class="featured-link">
			<i class="fa-solid fa-hand-pointer icon"></i>
			<span class="icon-text">Activate your account</span>
		</div>
		<div class="featured-link">
			<i class="fa-solid fa-microphone icon"></i>
			<span class="icon-text">Private Consulting</span>
		</div>
	</div>
</div>

<div class="about-section-container">
	<section class="about-section">
		<div class="about-section-slides">
			<div class="about-section-slides">
				<div class="about-section-image">
				</div>
				<div class="about-section-floating-box">
					<i class="fa-solid fa-arrow-trend-up"></i>
					<h4>Business Plan Formula</h4>
					<p>
						Lorem ipsum dolor consectetur elit noor adipiscing aquip.
					</p>
				</div>
			</div>
		</div>
		<div class="about-section-content">
			<div class="about-section-content-container">
				<h6 class="sub-heading">
					Who we are
				</h6>
				<h2>
					Solutions to Grow Your Business
				</h2>
				<p>
					Lorem ipsum dolor sit amet consectetur adipiscing elit do eiusmod tempor incididunt ut labore et dolore magna ut enim ad minim veniam nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
				</p>
				<ul>
					<li>
						<i class="fa-solid fa-check"></i>
						Business advisory service
					</li>
					<li>
						<i class="fa-solid fa-check"></i>
						Company incorporation
					</li>
					<li>
						<i class="fa-solid fa-check"></i>
						Accounting and investment
					</li>
				</ul>
				<div class="section-text-button">
					<a href="#" class="button button-secondary">Learn More</a>
				</div>
			</div>
		</div>
	</section>
</div>

<div class="workflow-section-container">
	<section class="workflow-section">
		<div class="workflow-section-heading">
			<h6 class="sub-heading">Workflow</h6>
			<h2>Advanced Business Strategy</h2>
		</div>
		<div class="workflow-section-tiles">
			<div class="workflow-section-tile">
				<div class="workflow-section-tile-icon">
					<i class="fa-solid fa-chart-line"></i>
				</div>
				<h4>
					Market Analytic
				</h4>
				<p>
					Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut elit tellus, luctus nec.
				</p>
			</div>
			<div class="workflow-section-tile">
				<div class="workflow-section-tile-icon">
					<i class="fa-solid fa-coins"></i>
				</div>
				<h4>
					Budget Control
				</h4>
				<p>
					Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut elit tellus, luctus nec.
				</p>
			</div>
			<div class="workflow-section-tile">
				<div class="workflow-section-tile-icon">
					<i class="fa-solid fa-rocket"></i>
				</div>
				<h4>
					Maximize Profit
				</h4>
				<p>
					Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut elit tellus, luctus nec.
				</p>
			</div>
		</div>
	</section>
</div>

<section class="section-with-image">
	<div class="section-text">
		<h6 class="sub-heading section-text-sub">
			Process
		</h6>
		<div class="section-text-heading section-text-sub">
			<h2>
				Business Process Automation
			</h2>
			<p>
				Lorem ipsum dolor sit amet consectetur adipiscing elit do eiusmod tempor incididunt ut  nisi ut aliquip ex ea commodo consequat.
			</p>
		</div>
		<div class="section-text-bullets section-text-sub">
			<div class="section-text-bullet">
					<div class="section-text-bullet-icon">
						<i class="fa-solid fa-layer-group"></i>
					</div>
					<div class="section-text-bullet-text">
						<h6>
							Strategic Planning
						</h6>
						<p>
							Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut elit tellus, luctus nec ullamcorper mattis.
						</p>
					</div>
			</div>
			<div class="section-text-bullet">
					<div class="section-text-bullet-icon">
						<i class="fa-solid fa-tv"></i>
					</div>
					<div class="section-text-bullet-text">
						<h6>
							Advanced Reporting
						</h6>
						<p>
							Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut elit tellus, luctus nec ullamcorper mattis.
						</p>
					</div>
			</div>
			<div class="section-text-bullet">
					<div class="section-text-bullet-icon">
						<i class="fa-solid fa-cart-shopping"></i>
					</div>
					<div class="section-text-bullet-text">
						<h6>
							Business Consulting
						</h6>
						<p>
							Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut elit tellus, luctus nec ullamcorper mattis.
						</p>
					</div>
			</div>
		</div>
		<div class="section-text-button section-text-sub">
			<a href="#" class="button button-secondary">Learn More</a>
		</div>
	</div>
	<div class="section-image">
		<%= image_tag asset_path('man-with-laptop.jpg') %>
	</div>
</section>

<div class="black-section-container">
	<section class="black-section">
		<div class="black-section-text">
			<div class="black-section-text-heading">
				<h3>
					Smart business strategy for major changes in global market trends.
				</h3>
			</div>
			<div class="black-section-text-normal">
				<div class="text-box">
					<h6 class="sub-heading">Partnership</h6>
					<p>
						Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut elit tellus luctus.
					</p>
				</div>
				<div class="text-box">
					<h6  class="sub-heading">Consultation</h6>
					<p>
						Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut elit tellus luctus.
					</p>
				</div>
			</div>
		</div>
		<div class="black-section-images">
			<div class="black-section-image image-1">
				<div class="background-overlay">
					<div class="black-section-image-content">
						<h6 class="sub-heading">Dashboard</h6>
						<h4>Market Analytic</h4>
						<div class="learn-more-button">
							<a href="#">Learn More</a>
						</div>
						<%= link_to "", root_path, class:"image-link" %>
					</div>
				</div>
			</div>
			<div class="black-section-image image-2">
				<div class="background-overlay">
					<div class="black-section-image-content">
						<h6 class="sub-heading">Strategy</h6>
						<h4>Digital Investment</h4>
						<div class="learn-more-button">
							<a href="#">Learn More</a>
						</div>
						<%= link_to "", root_path, class:"image-link" %>
					</div>
				</div>
			</div>
			<div class="black-section-image image-3">
				<div class="background-overlay">
					<div class="black-section-image-content">
						<h6 class="sub-heading">Solution</h6>
						<h4>Expert Consulting</h4>
						<div class="learn-more-button">
							<a href="#">Learn More</a>
						</div>
					</div>
						<%= link_to "", root_path, class:"image-link" %>
				</div>
			</div>
		</div>
	</section>
</div>

<p style="margin: 200px 0">
</p>
<div class="get-a-quote">
	<div class="background-overlay">
		<div class="get-a-quote-container">
			<h2 class="get-a-quote-text">
				Generate more sales with our smart business strategy
			</h2>
			<div class="action">
				<a href="#" class="button button-primary">Get Started</a>
			</div>
		</div>
	</div>
</div>